jasypt: # jasypt 配置
  encryptor:
    password: ${jasypt_encryptor_password} # 密钥
    algorithm: PBEWithMD5AndDES # 加密算法
    iv-generator-classname: org.jasypt.iv.NoIvGenerator # IV生成器类
    key-obtention-iterations: 1000 # 迭代次数
    pool-size: 1 # 池大小
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64 # 输出类型
mybatis-flex:
  admin-config:
    enable: false
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/iptv?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&connectTimeout=10000&socketTimeout=10000&autoReconnect=true&useSSL=false
      username: ENC(8YbVy8dnr99Xfm5Rbu4vvw==)
      password: ENC(gZL5yX/nN01bjgpeROhcQA==)
    postgresql:
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      username: ENC(1U13vEMl26nsx9Dl7eL6hxO6IDADD5CI)
      password: ENC(CL19XNR4HLl3PdInH8i3VA==)
spring:
  datasource: # JDBC 配置
    druid: # Druid 配置
      initial-size: 15 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 15 # 最小连接池数量
      max-active: 60 # 最大连接池数量
      max-wait: 60000 # 配置从连接池获取连接等待超时的时间
      keep-alive: true
      kill-when-socket-read-timeout: true
      socket-timeout: 600000 # socket超时时间 默认 10000ms
      connect-timeout: 10000 # 驱动配置连接超时时间，在连接的时候生效，默认值：10000ms
      phy-max-use-count: -1 # 最大的物理连接数，超过则会被强制回收，默认：-1（不建议配置）
      phy-timeout-millis: -1 # 连接的最大物理连接时长，超过则会被强制回收，默认：-1
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 连接保持空闲而不被驱逐的最小时间
      validation-query: SELECT 1 FROM DUAL # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query-timeout: 3000 # 单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
      test-while-idle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: false # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-pool-prepared-statement-per-connection-size: 20 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      useGlobalDataSourceStat: true  # 合并多个DruidDataSource的监控数据
      stat-view-servlet: #配置statViewFilter（配置Druid后台管理Servlet页面），用于展示Druid的统计信息
        enabled: true # sql监控开关
        url-pattern: /druid/* # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: true # 是否允许清空统计数据，重新计算  true:允许  false:不允许
        login-username: admin # 用户名
        login-password: 123456 # 密码
        allow: "" # 后台允许谁可以访问。默认就是允许所有访问。
        deny: "" # 后台禁止谁能访问
      web-stat-filter: # 配置WebStatFilter，用于采集web关联监控的数据
        enabled: true # web url监控
        session-stat-enable: true # session监控
        session-stat-max-count: 100 # session的最大个数，默认100
        url-pattern: /* # 过滤所有url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
      filters: stat,wall,slf4j # 属性类型是字符串,配置监控统计拦截的filters，去掉后监控界面sql无法统计，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
  # rabbitmq 配置
  rabbitmq:
    host: 127.0.0.1 #ip
    port: 5672      #
    #    addresses: 127.0.0.1:5672 #多个以逗号分隔，与host功能一样。
    username: guest #账号
    password: guest #密码
    virtualHost: iptv   #链接的虚拟主机
    requestedHeartbeat: 60s #指定心跳超时，单位秒，0为不指定；默认60s
    publisher-confirm-type: correlated #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调。 simple：同步等待confirm结果，直到超时；correlated：异步回调，定义ConfirmCallback，MQ返回结果时会回调这个ConfirmCallback
    publisherReturns: true  #是否启用消息被退回
    connectionTimeout: 30s #链接超时。单位ms。0表示无穷大不超时
    ### ssl相关
    ssl:
      enabled: false #是否支持ssl
      key-store: #指定持有SSL certificate的key store的路径
      key-store-type: #key store类型 默认PKCS12
      key-store-password: #指定访问key store的密码
      trust-store: #指定持有SSL certificates的Trust store
      trust-store-type: #默认JKS
      trust-store-password: #访问密码
      algorithm: #ssl使用的算法，例如，TLSv1.1
      verify-hostname: true #是否开启hostname验证
    ### cache相关
    cache:
      channel:
        size: 30 #缓存中保持的channel数量
        checkout-timeout: 60000 #当缓存数量被设置时，从缓存中获取一个channel的超时时间，单位毫秒；如果为0，则总是创建一个新channel
      connection:
        mode: channel #连接工厂缓存模式：CHANNEL 和 CONNECTION
    #        size: 10 #缓存的连接数，只有是CONNECTION模式时生效
    ### listener
    listener:
      type: simple #两种类型，SIMPLE，DIRECT
      ## simple类型
      simple:
        concurrency: 1  #最小消费者数量
        max-concurrency: 5 #最大的消费者数量
        missing-queues-fatal: true #是否停止容器当容器中的队列不可用
        ## 与direct相同配置部分
        auto-startup: true #是否自动启动容器
        acknowledge-mode: manual #表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
        prefetch: 1 #指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量
        default-requeue-rejected: true #决定被拒绝的消息是否重新入队；默认是true（与参数acknowledge-mode有关系）
        idle-event-interval: 10s #container events发布频率，单位ms
        ##重试机制
        retry:
          stateless: true #有无状态
          enabled: true  #是否开启
          max-attempts: 3 #最大重试次数,默认3
          initial-interval: 3s #重试间隔
          multiplier: 1 #对于上一次重试的乘数
          max-interval: 10s #最大重试时间间隔
      direct:
        consumers-per-queue: 10 #每个队列消费者数量
        missing-queues-fatal: false #若容器声明的队列在代理上不可用，是否失败.
      #        #...其余配置看上方公共配置
    ## template相关
    template:
      mandatory: true #是否启用强制信息；默认false。定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息
      receive-timeout: 30s #`receive()`接收方法超时时间
      reply-timeout: 30s #`sendAndReceive()`超时时间
      #      exchange: #默认的交换机
      #      routingKey: #默认的路由
      #      defaultReceiveQueue: #默认的接收队列
      ## retry重试相关
      retry:
        enabled: true #是否开启
        max-attempts: 3 #最大重试次数
        initial-interval: 3s #重试间隔
        multiplier: 1 #失败间隔乘数
        max-interval: 10s #最大间隔
bilibili:
  live:
    base-url: http://192.168.1.2:8911/live/bilibili/