jasypt: # jasypt 配置
  encryptor:
    password: ${jasypt_encryptor_password} # 密钥
    algorithm: PBEWithMD5AndDES # 加密算法
    iv-generator-classname: org.jasypt.iv.NoIvGenerator # IV生成器类
    key-obtention-iterations: 1000 # 迭代次数
    pool-size: 1 # 池大小
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64 # 输出类型
